// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auaqotbuexfytlcucamb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1YXFvdGJ1ZXhmeXRsY3VjYW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTg4NTEsImV4cCI6MjA3Nzc3NDg1MX0.RonHkXyKe5pdjft_ESYYoMkcraabd4uRgPhFoEMBHpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});